# Generated by Django 4.2.20 on 2025-04-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'day')},
        ),
    ]
