# Generated by Django 4.2.20 on 2025-04-07 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_menu_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('employee', 'restaurant', 'day')},
        ),
    ]
