# Generated by Django 4.2.20 on 2025-04-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='menu',
        ),
    ]
