# Generated by Django 4.2.20 on 2025-04-07 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0003_remove_vote_menu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('employee', 'day')},
        ),
    ]
